import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { description } = await req.json();

    if (!description) {
      return new Response(JSON.stringify({ error: "Description input is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
    if (!GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: "GEMINI_API_KEY not set in Supabase secrets." }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const prompt = `You are a form field generator. Based on the user's description, generate a JSON array of form field objects. Each object should conform to the following TypeScript interface:
\`\`\`typescript
export type FormFieldType =
  | "text"
  | "email"
  | "number"
  | "textarea"
  | "checkbox"
  | "select"
  | "radio"
  | "sentiment-text";

export interface FormField {
  name: string;
  label: string;
  type: FormFieldType;
  placeholder?: string;
  defaultValue?: any;
  required?: boolean;
  minLength?: number;
  maxLength?: number;
  pattern?: RegExp; // For custom regex validation
  options?: { label: string; value: string | number }[]; // For select and radio fields
  description?: string;
}
\`\`\`
For 'select' and 'radio' types, ensure 'options' is an array of { label: string; value: string | number }.
If the user asks for a field that would benefit from sentiment analysis (e.g., feedback, comments, review), use the 'sentiment-text' type.
Ensure 'name' is a camelCase string suitable for a form field identifier.
Respond with only the JSON array, no other text.

User description: "${description}"
`;

    const geminiResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${GEMINI_API_KEY}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: prompt },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
        },
      }),
    });

    if (!geminiResponse.ok) {
      const errorData = await geminiResponse.json();
      console.error("Gemini API error:", errorData);
      return new Response(JSON.stringify({ error: errorData.error?.message || "Failed to generate form fields from Gemini." }), {
        status: geminiResponse.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await geminiResponse.json();
    const generatedContent = data.candidates[0]?.content?.parts[0]?.text;

    if (!generatedContent) {
      return new Response(JSON.stringify({ error: "No content generated by Gemini." }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Gemini might wrap the JSON in a code block, try to extract it
    let jsonString = generatedContent;
    const jsonMatch = generatedContent.match(/```json\n([\s\S]*?)\n```/);
    if (jsonMatch && jsonMatch[1]) {
      jsonString = jsonMatch[1];
    }

    const fields = JSON.parse(jsonString);

    // Basic validation to ensure it's an array of objects
    if (!Array.isArray(fields) || !fields.every(item => typeof item === 'object' && item !== null)) {
      throw new Error("Generated content is not a valid JSON array of objects.");
    }

    return new Response(JSON.stringify({ fields }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error in generate-form-fields function:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});